version: '3'
services:
  app-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=market_place_2
      - MYSQL_ROOT_HOST= %
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app-redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    restart: always
  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=app-mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=market_place_2
      - REDIS_HOST=app-redis
      - GIN_MODE=release
    restart: always
    depends_on:
      - app-mysql
      - app-redis
