version: '3'
services:
  app-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=models
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      - DATABASE_HOST=app-mysql
      - DATABASE_PORT=3308
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=models
    restart: always
    depends_on:
      - app-mysql
